// Code generated by go-swagger; DO NOT EDIT.

package auths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	stderrors "errors"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/go_otus_additionals/go_bas/4_5__23__09_2025_swagger/from_swagger_to_code/models"
)

// NewPostLoginParams creates a new PostLoginParams object
//
// There are no default values defined in the spec.
func NewPostLoginParams() PostLoginParams {

	return PostLoginParams{}
}

// PostLoginParams contains all the bound params for the post login operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostLogin
type PostLoginParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Модель которую принимает метод (Param)
	  Required: true
	  In: body
	*/
	Input *models.ModelsLoginRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostLoginParams() beforehand.
func (o *PostLoginParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer func() {
			_ = r.Body.Close()
		}()
		var body models.ModelsLoginRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if stderrors.Is(err, io.EOF) {
				res = append(res, errors.Required("input", "body", ""))
			} else {
				res = append(res, errors.NewParseError("input", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Input = &body
			}
		}
	} else {
		res = append(res, errors.Required("input", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
