// Code generated by go-swagger; DO NOT EDIT.

// Package restapi auth server
//
//	API Server
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /
//	Version: 1
//	Contact:
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
